version: '3.8'
services:
  dev:
    build: .
    working_dir: /app
    privileged: true
    volumes:
      - ./src:/app
      - .:/subject
    command: /bin/sh -c "while true; do sleep 1000; done"
    environment:
      - TRUNK_MONKEY_SOURCES_ROOT=/subject